"""add_videos_and_likes_tables

Revision ID: 2a5cf69ce82e
Revises: f1ec05db8dc3
Create Date: 2025-10-09 14:11:17.220750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5cf69ce82e'
down_revision: Union[str, Sequence[str], None] = 'f1ec05db8dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('youtube_id', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_like_count'), 'videos', ['like_count'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_videos_uploaded_by_user_id'), 'videos', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_videos_youtube_id'), 'videos', ['youtube_id'], unique=True)
    op.create_index(op.f('ix_videos_youtube_url'), 'videos', ['youtube_url'], unique=True)
    op.create_table('video_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'user_id', name='uq_video_user_like')
    )
    op.create_index(op.f('ix_video_likes_user_id'), 'video_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_likes_video_id'), 'video_likes', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_likes_video_id'), table_name='video_likes')
    op.drop_index(op.f('ix_video_likes_user_id'), table_name='video_likes')
    op.drop_table('video_likes')
    op.drop_index(op.f('ix_videos_youtube_url'), table_name='videos')
    op.drop_index(op.f('ix_videos_youtube_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_uploaded_by_user_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_like_count'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
