"""add_created_at_to_users

Revision ID: 38074cde39da
Revises: 57356509d93f
Create Date: 2026-05-01 22:04:41.850336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38074cde39da'
down_revision: Union[str, Sequence[str], None] = '57356509d93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add as nullable first so existing rows don't violate NOT NULL
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # Backfill existing rows with today's date
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    # Now enforce NOT NULL
    op.alter_column('users', 'created_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
