"""add_contact_messages_table

Revision ID: 57356509d93f
Revises: c2a5d8f10b43
Create Date: 2026-05-01 21:48:31.375736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57356509d93f'
down_revision: Union[str, Sequence[str], None] = 'c2a5d8f10b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_event_reports_status'), table_name='event_reports')
    op.create_index(op.f('ix_event_reports_user_id'), 'event_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_reports_user_id'), table_name='event_reports')
    op.create_index(op.f('ix_event_reports_status'), 'event_reports', ['status'], unique=False)
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
