"""add_multiple_categories_and_organizers

Revision ID: ee438735edba
Revises: 97b1c02e13e7
Create Date: 2025-10-25 14:13:22.300296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee438735edba'
down_revision: Union[str, Sequence[str], None] = '97b1c02e13e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_events', sa.Column('all_categories', sa.Text(), nullable=True))
    op.add_column('race_events', sa.Column('all_organizers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_events', 'all_organizers')
    op.drop_column('race_events', 'all_categories')
    # ### end Alembic commands ###
